"""Add is_active column to auctions

Revision ID: 6578c2840e1a
Revises: 490afe4f2dec
Create Date: 2025-01-16 19:06:01.062507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6578c2840e1a'
down_revision: Union[str, None] = '490afe4f2dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'is_active')
    # ### end Alembic commands ###

