"""Add img column to auctions table

Revision ID: f1bbbf4a0cab
Revises: 6578c2840e1a
Create Date: 2025-01-26 13:51:53.289379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bbbf4a0cab'
down_revision: Union[str, None] = '6578c2840e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add the column with a default value
    op.add_column('auctions', sa.Column('img', sa.String(), nullable=False, server_default='default_image.png'))
    # Remove the default after the column is added
    op.alter_column('auctions', 'img', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'img')
    # ### end Alembic commands ###
